
sudo: required
services:
   - docker

before_install:
   docker build -t syed/react-test -f ./client/Dockerfile.dev ./client

scripts:
   - docker run -e CI=true syed/react-test npm test 

after_success: 
   - docker build -t syedrahmandevops/multi-client ./client
   - docker build -t syedrahmandevops/multi-server ./server
   - docker build -t syedrahmandevops/multi-nginx ./nginx
   - docker build -t syedrahmandevops/multi-worker ./worker    
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   - docker push syedrahmandevops/multi-client
   - docker push syedrahmandevops/multi-server
   - docker push syedrahmandevops/multi-nginx
   - docker push syedrahmandevops/multi-worker 

